modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Simulated Team"
description='''
An addon for Create: Simulated (Aeronautics) that adds inverted redstone output functionality to the Navigation Table.
Right-click a Navigation Table with a Redstone Torch to toggle inverted mode.
In inverted mode, all four sides output redstone power, except the side pointing toward the target.
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="simulated"
type="required"
versionRange="[${simulated_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="sable"
type="required"
versionRange="[${sable_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
type="required"
versionRange="[6.0.10,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="createbigcannons"
type="required"
versionRange="[5.11.3,)"
ordering="AFTER"
side="BOTH"
